version: "3.7"
services:

  aggregator_xai:
    image: openfl_xai/aggregator
    container_name: aggregator_xai
    environment:
      - PYTHONUNBUFFERED=1
    
  col0:
    image: openfl_xai/collaborator
    depends_on:
     - aggregator_xai
    container_name: col0
    volumes:
      - ./certificates/col0_cert_folder.zip:/current_workspace/col0_cert_folder.zip
      - ./data/col0_data.zip:/current_workspace/data/col0_data.zip
    command:
      - /bin/sh
      - -c
      - |
        unzip -n /current_workspace/col0_cert_folder.zip
        unzip -o /current_workspace/data/col0_data.zip -d /current_workspace/data
        python3 start_collaborator.py
    environment:
      - COLLABORATOR_NAME=col0
      - PYTHONUNBUFFERED=1

  col1:
    image: openfl_xai/collaborator
    depends_on:
     - aggregator_xai
    container_name: col1
    volumes:
      - ./certificates/col1_cert_folder.zip:/current_workspace/col1_cert_folder.zip
      - ./data/col1_data.zip:/current_workspace/data/col1_data.zip
    command:
      - /bin/sh
      - -c
      - |
        unzip -n /current_workspace/col1_cert_folder.zip
        unzip -o /current_workspace/data/col1_data.zip -d /current_workspace/data
        python3 start_collaborator.py
    environment:
      - COLLABORATOR_NAME=col1
      - PYTHONUNBUFFERED=1


  col2:
    image: openfl_xai/collaborator
    depends_on:
     - aggregator_xai
    container_name: col2
    volumes:
      - ./certificates/col2_cert_folder.zip:/current_workspace/col2_cert_folder.zip
      - ./data/col2_data.zip:/current_workspace/data/col2_data.zip
    command:
      - /bin/sh
      - -c
      - |
        unzip -n /current_workspace/col2_cert_folder.zip
        unzip -o /current_workspace/data/col2_data.zip -d /current_workspace/data
        python3 start_collaborator.py
    environment:
      - COLLABORATOR_NAME=col2
      - PYTHONUNBUFFERED=1


  col3:
    image: openfl_xai/collaborator
    depends_on:
     - aggregator_xai
    container_name: col3
    volumes:
      - ./certificates/col3_cert_folder.zip:/current_workspace/col3_cert_folder.zip
      - ./data/col3_data.zip:/current_workspace/data/col3_data.zip
    command:
      - /bin/sh
      - -c
      - |
        unzip -n /current_workspace/col3_cert_folder.zip
        unzip -o /current_workspace/data/col3_data.zip -d /current_workspace/data
        python3 start_collaborator.py
    environment:
      - COLLABORATOR_NAME=col3
      - PYTHONUNBUFFERED=1


  col4:
    image: openfl_xai/collaborator
    depends_on:
     - aggregator_xai
    container_name: col4
    volumes:
      - ./certificates/col4_cert_folder.zip:/current_workspace/col4_cert_folder.zip
      - ./data/col4_data.zip:/current_workspace/data/col4_data.zip
    command:
      - /bin/sh
      - -c
      - |
        unzip -n /current_workspace/col4_cert_folder.zip
        unzip -o /current_workspace/data/col4_data.zip -d /current_workspace/data
        python3 start_collaborator.py
    environment:
      - COLLABORATOR_NAME=col4
      - PYTHONUNBUFFERED=1
